In [1]:
import numpy as np
import pandas as pd
import random
df = pd.read_csv("nameExtractor.csv", sep=',', encoding='utf-8')
df.head(10)

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor
5,6,Calvin,Ramsey,Female,loretta85@example.com,001-314-829-5014x1792,31-08-17,Therapeutic radiographer
6,7,Collin,Allison,Male,yvaughn@example.net,(314)591-7413,21-11-79,Administrator
7,8,Nicholas,Branch,Male,greerjimmy@example.net,-7199,21-01-06,Fisheries officer
8,9,Emma,Robinson,Female,charleshiggins@example.org,166-234-6882x7457,19-03-09,Haematologist
9,10,Pedro,Cordova,Male,leslie08@example.com,(389)824-3204x8287,17-06-08,Phytotherapist

In [2]:
#name
first_name = df["First Name"].dropna().tolist()
last_name = df["Last Name"].dropna().tolist()

pengali_first = (5000 // len(first_name)) + 1
pengali_last = (5000 // len(last_name)) + 1

first_names_extended = (first_name * pengali_first)[:5000]
last_names_extended = (last_name * pengali_last)[:5000]

random.shuffle(first_names_extended)
random.shuffle(last_names_extended)

hasil = []
for i in range(5000):
    fn = first_names_extended[i]
    ln = last_names_extended[i]
    hasil.append({
        "cust_id": f"{i+1:04d}",
        "First Name": fn,
        "Last Name": ln,
        "Full Name": f"{fn} {ln}"
    })

#contact
nomor_telepon = []
for _ in range(5000):
    acak = "".join([str(random.randint(0, 9)) for _ in range(10)])
    nomor = "08" + acak
    nomor_telepon.append(nomor)
df_telepon = pd.DataFrame(nomor_telepon, columns=["Nomor Telepon"])

df_final = pd.DataFrame(hasil)
df_final["Nomor Telepon"] = df_telepon["Nomor Telepon"]
df_final.head(10)

  cust_id First Name Last Name          Full Name Nomor Telepon
0    0001    Michael   Compton    Michael Compton  086008767950
1    0002  Elizabeth   Sanchez  Elizabeth Sanchez  089084119432
2    0003    Michele    Ortega     Michele Ortega  087911861903
3    0004     Alisha   Shannon     Alisha Shannon  085580186796
4    0005     Leslie  Roberson    Leslie Roberson  081025617131
5    0006      Alice   Simpson      Alice Simpson  081800984200
6    0007       Jake     Zhang         Jake Zhang  081885473429
7    0008      Frank    Lester       Frank Lester  081247832995
8    0009        Don  Hatfield       Don Hatfield  086643929301
9    0010      Kevin    Bowers       Kevin Bowers  088068124925

In [3]:
df_final.to_csv("name.csv", index=False, encoding='utf-8')